---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: devstaff-k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi